### ISSUE TITLE
advice for using adaptive

### ISSUE THREAD

**Issue by dchudz** [coiled/feedback#194]
These are some default settings for adaptive in distributed:

```
  adaptive:
    interval: 1s         # Interval between scaling evaluations
    target-duration: 5s  # Time an entire graph calculation is desired to take ("1m", "30m")
    minimum: 0           # Minimum number of workers
    maximum: .inf        # Maximum number of workers
    wait-count: 3        # Number of times a worker should be suggested for removal before removing it
```

For Coiled (which launches instances in minutes...) these target durations are way too fast.

Something like this would be better:

```
adaptive:
    interval: 10s
    target-duration: 210s
```

Coiled ought to implement these better defaults in our clusters, but in the meantime a user can set them via:

`cluster coiled.Cluster(..., environ={"DASK_DISTRIBUTED__SCHEDULER__ADAPTIVE__INTERVAL": "10s", "DASK_DISTRIBUTED__SCHEDULER__ADAPTIVE__TARGET_DURATION": "210s"})`

Note that most users haven't used adaptive with Coiled, so this is a little bit experimental.
